name: whatsapp_frontend
version: 0.1.0
environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  flutter_secure_storage: ^9.2.4

flutter:
  uses-material-design: true
  assets:
    - assets/config.json
